### ISSUE TITLE
Audit :USDC price hardcoded to 1 $.

### ISSUE THREAD

**Issue by supernovahs** [Anish-Agnihotri/Hyperbitcoinization#1]
There is a potential risk of USDC depeg . partyUSDC could add 1 million USDC even though they are worth (say $900k).

Recommendation:
Use chainlink price feed to ensure  partyUSDC deposits >= $1 million USDC worth of tokens at the time of deposit.

**Comment by ameya-deshmukh** [comment]
The price feed is BTC/USD and not BTC/USDC, so this isn't really required. Would appreciate insights from @Anish-Agnihotri

**Comment by supernovahs** [comment]
When party deposits 1000_000 USDC, there is not check whether the partyUSDC actually spent $1million dollars.
Since the USDC depeg , you cannot assume this.

**Comment by Anish-Agnihotri** [comment]
Interesting problem, more relevant now with the recent depeg.

In the interest of Balaji's bet, I'd say to probably keep it w/ USDC without the price feed, since we're assuming best intentions. Plus, the funds are locked for 90 days, at least, so there can be a depeg at time of claim that we can't account for anyways.

Still, it's good to flag, so I've added to the README, thank you!

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
thatbreezedev, @devyuhan, @Wert1996, @adilcpm, @klevlen, @nickbalestra, @yuki-js, @jlugaro, @Maverick9081, @124t, @ascendantaditya, @0xtristan, @richiebijoy, @philosphi, @Anish-Agnihotri, @RusseII, @ezaruba, @liqwik, @Sandalots, @Abd010, @codebender828, @Farzzn, @mxinyi, @SaratAngajalaoffl, @kelonye, @fanyilun0, @KTruong008, @Imdormi, @jordanlepera, @nkootstra, @Nanak360, @unixpi, @kaustubh43, @ngarnica23, @clarkezone, @gooshi1, @anaMaya57, @phuongwd, @likhonsible, @b1xt, @rsharvesh16, @deiondz, @mattdeco, @ri-dev-git, @iSouvikKhan, @enzotar, @vadorovsky, @g153xx, @0xqd, @ibrixxxshreejitverma, @fluturecode, @dattgoswami, @thanhphuoc95, @sayantank, @nikhilesh1234, @AlienCode4, @MoneyBoy1x, @result17, @cubix1222, @spantheslayer, @ohari5336, @aspnxdd, @Ykumar1415, @andyluss, @userdarius, @phuclong304, @Ashishsingh009, @Pulko, @GauravKanwat, @anikdhabal, @Restuta, @salman1977, @Sudhanva-Nadiger, @RichMix, @lakshaywadhwacse, @chrajeshdagur, @charann29, @yogendrarana, @sujayxaradhya, @tcchawla, @skynetcap, @wentokay, @ardika24, @tuvudu, @bryantanjw, @viveknariya, @anthontaylor, @kevinrodriguez-io, @ryanberckmans, @chengyuefeng1993, @zfaizal2, @Royalesri, @chernebeats, @YuChocopie, @Gabulhas, @sixvxsh, @yamen, @NicoHinderling, @mfragersudo-JSON, @C-L-0-U-D, @SRi-iRS, @salman1977, @nabeel99, @mastercyb, @hritikchaudhary, @0xMukesh, @hasthik, @URvesh109, @RustySol, @knightmate, @vbalien, @Animesh-23, @4hourwork, @ozyman42, @0xSense, @pcaversaccio, @augustin-cheron, @codeusb, @aabidsofi19, @rahulnema0411, @pengsol, @ph101pp, @patriciobcs, @anikaitprasar, @DezorkIT, @BhavikSojitra, @warmherz, @anton-karlovskiy, @agungsantoso, @256hax, @0xluckycoder, @NemesisLW, @mertimus, @ethman2, @basantbhandari, @rahulsm20, @val-samonte, @kesne, @sk1122, @shubhampatel27, @k3ithloh, @yacoub-harkati, @viveknariya, @0xethsign, @fabOnReact, @m4thfr34k, @Narasimha1997, @samuelj90
